### ISSUE TITLE
Break Apart Global Database

### ISSUE THREAD

**Issue by Redrield** [FRCDiscord/Dozer#123]
Currently, commands such as [&setteam](https://github.com/FRCDiscord/Dozer/blob/master/dozer/cogs/teams.py#L11) provide their functionality by writing information into a _global_ sqlite database held by Dozer. This means that actions taken with Dozer in DMs, or on secondary guilds affects the perception of the user in the database _for all guilds_ that the bot is a part of. Information of a user should be kept _per guild_, not globally. Actions on one guild should not affect the information being stored with regards to the user in a different guild.

**Comment by tweirtx** [comment]
Is this because of the whole setting random teams thing?

**Comment by Redrield** [comment]
That's a part of it, but any user-facing command that modifies the database has the same issue

**Comment by tweirtx** [comment]
Here are my multiple reasons for shutting this down:
0. It's horribly inefficient to have 37+ database connections up with the library that we are using, especially since it's not asynchronous. Also we're switching to Postgres soon so...lets not.
1. It would require rewriting big chunks, if not most of the bot. I don't think it's fair to rewrite over one little issue of you wanting to set your Dozer team numbers to 1285929527484263283844. If you want to do that then a Dozer setup guide is in the README.
2. Most user data already guild separates. Just look at the DB table classes in the bottom of each cog. Notice how most of them usually contain a variable for guild is.
If any of your reasons aren't covered by mine let me know.
