### ISSUE TITLE
Option to turn on force-enabling push to talk after a certain number of people are in a vc channel

### ISSUE THREAD

**Issue by tweirtx** [FRCDiscord/Dozer#172]

**Comment by AidanFromProgramming** [comment]
Working on it

**Comment by AidanFromProgramming** [comment]
Still working on request, but feature will not work as intended because discord does not auto enable ptt when it is required. Submitted [feature request](https://support.discord.com/hc/en-us/community/posts/360050786914-Push-to-talk-should-temporarily-auto-enable-in-channels-that-require-it)  to discord but no guarantee that it will be satisfied.
