### ISSUE TITLE
When setting up python, it crashes expecting postgres and wont generate config

### ISSUE THREAD

**Issue by jreneew2** [FRCDiscord/Dozer#179]
Hi, I am trying to set this up on an Ubuntu 18.04 server and can't seem to get it working. I have installed Postgres and all the requirements, but when I run 

```
python -m dozer
```

it gives me this error:

```
ValueError: invalid DSN: scheme is expected to be either "postgresql" or "postgres", got 'sqlite'
```

I'm not sure where I am messing up. It won't generate a config file either

Thanks!

**Comment by tweirtx** [comment]
I see the problem, I'll push a fix

**Comment by bkeeneykid** [comment]
Looks like we've got the order of our init process a bit wrong for this to happen. If you want to get working in the meantime, you can take the following JSON string and put this in a file named `config.json` in the root folder:
```
{
   "prefix":"&",
   "developers":[

   ],
   "tba":{
      "key":""
   },
   "toa":{
      "key":"Put TOA API key here",
      "app_name":"Dozer"
   },
   "db_url":"postgres://user:password@host:port",
   "gmaps_key":"PUT GOOGLE MAPS API KEY HERE",
   "discord_token":"Put Discord API Token here.",
   "is_backup":false
}````
Past then, modify the DB url so that it's valid with the `postgres://user:password@host:port` format.

**Comment by jreneew2** [comment]
That's what I ended up doing and I got it running!

Thanks for the quick response
