### ISSUE TITLE
Make Mutes and Deafens role-based instead of override-based

### ISSUE THREAD

**Issue by bkeeneykid** [FRCDiscord/Dozer#225]
This makes mutes and deafens significantly faster (past the first attempt) and would reduce the strain on the bot and the connection to discord significantly. Would require storing the role ID for the two methods and would likely require a check that no new channels have appeared since the last mute/deafen, but should also fix a few outstanding issues as well such as #193

**Comment by open-sourceress** [comment]
When a role is granted send permissions on a channel, denying send permission to a 'Muted' role won't mute users in that channel because of [how Discord combines channel overwrites](https://discord.com/developers/docs/topics/permissions#permission-overwrites). Using a role to deny permissions will require a workaround for this.

**Comment by AidanFromProgramming** [comment]
IIRC if a role is above all of the other roles in a channel, it the mute role has send permissions disabled then it would mute the user

**Comment by open-sourceress** [comment]
Discord's documentation that I linked earlier says otherwise, and a quick test seems to support the docs.
